//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Committed rather than generated into obj/ on purpose. WPF compiles a XAML file that names a type
// of its own assembly in a second pass, through a temporary project that carries only the plain
// Compile items of this one - never the sources a task adds during PrepareResources. A designer
// generated into obj/ is therefore invisible to {x:Static res:Strings.*}, and the pass-2 build fails
// with CS0103. Visual Studio keeps this file in step through the PublicResXFileCodeGenerator
// declared on Strings.resx in the .csproj; after editing the .resx outside Visual Studio, regenerate
// it (or add the member by hand - it is one property per key).

namespace RemoteDeck.App.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteDeck.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Common_Domain {
            get {
                return ResourceManager.GetString("Common_Domain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to * required.
        /// </summary>
        public static string Common_RequiredHint {
            get {
                return ResourceManager.GetString("Common_RequiredHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        public static string Common_DeleteFailedTitle {
            get {
                return ResourceManager.GetString("Common_DeleteFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search  (Ctrl+F).
        /// </summary>
        public static string Pane_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Pane_SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Pane_New {
            get {
                return ResourceManager.GetString("Pane_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New connection (Ctrl+N).
        /// </summary>
        public static string Pane_NewToolTip {
            get {
                return ResourceManager.GetString("Pane_NewToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import connections from .rdp files or the Remote Desktop history.
        /// </summary>
        public static string Pane_ImportToolTip {
            get {
                return ResourceManager.GetString("Pane_ImportToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved connections are unavailable: the database could not be opened. See the log..
        /// </summary>
        public static string Pane_Unavailable {
            get {
                return ResourceManager.GetString("Pane_Unavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ★ Favorites.
        /// </summary>
        public static string Pane_GroupFavorites {
            get {
                return ResourceManager.GetString("Pane_GroupFavorites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ungrouped.
        /// </summary>
        public static string Pane_GroupUngrouped {
            get {
                return ResourceManager.GetString("Pane_GroupUngrouped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No connections yet — press Ctrl+N to add one..
        /// </summary>
        public static string Pane_EmptyDefault {
            get {
                return ResourceManager.GetString("Pane_EmptyDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No connection matches “{0}”..
        /// </summary>
        public static string Pane_EmptyNoMatch {
            get {
                return ResourceManager.GetString("Pane_EmptyNoMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Pane_StatusConnected {
            get {
                return ResourceManager.GetString("Pane_StatusConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reconnecting.
        /// </summary>
        public static string Pane_StatusReconnecting {
            get {
                return ResourceManager.GetString("Pane_StatusReconnecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Pane_StatusOffline {
            get {
                return ResourceManager.GetString("Pane_StatusOffline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show or hide the connection pane (Ctrl+B).
        /// </summary>
        public static string Shell_PaneToggleToolTip {
            get {
                return ResourceManager.GetString("Shell_PaneToggleToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No session.
        /// </summary>
        public static string Shell_NoSession {
            get {
                return ResourceManager.GetString("Shell_NoSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Shell_Reconnect {
            get {
                return ResourceManager.GetString("Shell_Reconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect this session again.
        /// </summary>
        public static string Shell_ReconnectToolTip {
            get {
                return ResourceManager.GetString("Shell_ReconnectToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop the scheduled reconnection.
        /// </summary>
        public static string Shell_CancelRetryToolTip {
            get {
                return ResourceManager.GetString("Shell_CancelRetryToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy diagnostics for this session to the clipboard.
        /// </summary>
        public static string Shell_DiagnosticsToolTip {
            get {
                return ResourceManager.GetString("Shell_DiagnosticsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage credentials.
        /// </summary>
        public static string Shell_CredentialsToolTip {
            get {
                return ResourceManager.GetString("Shell_CredentialsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Shell_Disconnect {
            get {
                return ResourceManager.GetString("Shell_Disconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a connection and press Enter.
        /// </summary>
        public static string Shell_EmptySessions {
            get {
                return ResourceManager.GetString("Shell_EmptySessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} — {1} · {2}.
        /// </summary>
        public static string Shell_SessionLabel {
            get {
                return ResourceManager.GetString("Shell_SessionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Remote Desktop control found.
        /// </summary>
        public static string Shell_NoControlTitle {
            get {
                return ResourceManager.GetString("Shell_NoControlTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None of the known mstscax.dll CLSIDs is registered on this machine..
        /// </summary>
        public static string Shell_NoControlMessage {
            get {
                return ResourceManager.GetString("Shell_NoControlMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts unavailable.
        /// </summary>
        public static string Shell_ShortcutsUnavailableTitle {
            get {
                return ResourceManager.GetString("Shell_ShortcutsUnavailableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Ctrl+Alt+Left / Ctrl+Alt+Right still release the focus. See {1}..
        /// </summary>
        public static string Shell_ShortcutsUnavailableMessage {
            get {
                return ResourceManager.GetString("Shell_ShortcutsUnavailableMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RDP control v{0} ready.
        /// </summary>
        public static string Shell_ReadyTitle {
            get {
                return ResourceManager.GetString("Shell_ReadyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick a connection and press Enter, or press Ctrl+N to create one..
        /// </summary>
        public static string Shell_ReadyMessage {
            get {
                return ResourceManager.GetString("Shell_ReadyMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database unavailable.
        /// </summary>
        public static string Shell_DatabaseUnavailableTitle {
            get {
                return ResourceManager.GetString("Shell_DatabaseUnavailableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved connections cannot be read, so nothing can be connected. See {0}..
        /// </summary>
        public static string Shell_DatabaseUnreadableMessage {
            get {
                return ResourceManager.GetString("Shell_DatabaseUnreadableMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connections cannot be edited until the database opens..
        /// </summary>
        public static string Shell_DatabaseNoEditMessage {
            get {
                return ResourceManager.GetString("Shell_DatabaseNoEditMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connections cannot be deleted until the database opens..
        /// </summary>
        public static string Shell_DatabaseNoDeleteMessage {
            get {
                return ResourceManager.GetString("Shell_DatabaseNoDeleteMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connections cannot be imported until the database opens..
        /// </summary>
        public static string Shell_DatabaseNoImportMessage {
            get {
                return ResourceManager.GetString("Shell_DatabaseNoImportMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credentials cannot be managed until the database opens..
        /// </summary>
        public static string Shell_DatabaseNoCredentialsMessage {
            get {
                return ResourceManager.GetString("Shell_DatabaseNoCredentialsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} intercepted.
        /// </summary>
        public static string Shell_ShortcutInterceptedTitle {
            get {
                return ResourceManager.GetString("Shell_ShortcutInterceptedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to via {0} — no action is wired to it yet.
        /// </summary>
        public static string Shell_ShortcutInterceptedMessage {
            get {
                return ResourceManager.GetString("Shell_ShortcutInterceptedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no tab to close..
        /// </summary>
        public static string Shell_NoTabToCloseMessage {
            get {
                return ResourceManager.GetString("Shell_NoTabToCloseMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no tab to reconnect..
        /// </summary>
        public static string Shell_NoTabToReconnectMessage {
            get {
                return ResourceManager.GetString("Shell_NoTabToReconnectMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RDP session unavailable.
        /// </summary>
        public static string Shell_SessionUnavailableTitle {
            get {
                return ResourceManager.GetString("Shell_SessionUnavailableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No usable Remote Desktop control was found at startup. See {0}..
        /// </summary>
        public static string Shell_SessionUnavailableMessage {
            get {
                return ResourceManager.GetString("Shell_SessionUnavailableMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect failed.
        /// </summary>
        public static string Shell_ConnectFailedTitle {
            get {
                return ResourceManager.GetString("Shell_ConnectFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (0x{1}): {2}.
        /// </summary>
        public static string Shell_ConnectFailedMessage {
            get {
                return ResourceManager.GetString("Shell_ConnectFailedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics copied.
        /// </summary>
        public static string Shell_DiagnosticsCopiedTitle {
            get {
                return ResourceManager.GetString("Shell_DiagnosticsCopiedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The state of '{0}' is on the clipboard..
        /// </summary>
        public static string Shell_DiagnosticsCopiedMessage {
            get {
                return ResourceManager.GetString("Shell_DiagnosticsCopiedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics not copied.
        /// </summary>
        public static string Shell_DiagnosticsNotCopiedTitle {
            get {
                return ResourceManager.GetString("Shell_DiagnosticsNotCopiedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The clipboard refused the text ({0})..
        /// </summary>
        public static string Shell_DiagnosticsNotCopiedMessage {
            get {
                return ResourceManager.GetString("Shell_DiagnosticsNotCopiedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection deleted.
        /// </summary>
        public static string Shell_ConnectionDeletedTitle {
            get {
                return ResourceManager.GetString("Shell_ConnectionDeletedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' is gone..
        /// </summary>
        public static string Shell_ConnectionDeletedMessage {
            get {
                return ResourceManager.GetString("Shell_ConnectionDeletedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete '{0}'?.
        /// </summary>
        public static string Shell_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("Shell_DeleteConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press Delete again to confirm..
        /// </summary>
        public static string Shell_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("Shell_DeleteConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closing '{0}'….
        /// </summary>
        public static string Shell_ClosingConnectionTitle {
            get {
                return ResourceManager.GetString("Shell_ClosingConnectionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Its session is closed before the connection is deleted..
        /// </summary>
        public static string Shell_ClosingConnectionMessage {
            get {
                return ResourceManager.GetString("Shell_ClosingConnectionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closing {0} session….
        /// </summary>
        public static string Shell_ClosingSessionsOne {
            get {
                return ResourceManager.GetString("Shell_ClosingSessionsOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closing {0} sessions….
        /// </summary>
        public static string Shell_ClosingSessionsMany {
            get {
                return ResourceManager.GetString("Shell_ClosingSessionsMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close this session (Ctrl+W).
        /// </summary>
        public static string Session_CloseToolTip {
            get {
                return ResourceManager.GetString("Session_CloseToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' disconnected.
        /// </summary>
        public static string Session_DisconnectedTitle {
            get {
                return ResourceManager.GetString("Session_DisconnectedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        public static string Session_ConnectingTitle {
            get {
                return ResourceManager.GetString("Session_ConnectingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        public static string Session_ConnectedTitle {
            get {
                return ResourceManager.GetString("Session_ConnectedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' interrupted — {1}.
        /// </summary>
        public static string Session_InterruptedTitle {
            get {
                return ResourceManager.GetString("Session_InterruptedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to connection lost.
        /// </summary>
        public static string Session_ConnectionLost {
            get {
                return ResourceManager.GetString("Session_ConnectionLost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to attempt {0} of {1}.
        /// </summary>
        public static string Session_AttemptProgress {
            get {
                return ResourceManager.GetString("Session_AttemptProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Session_CountdownWithProgress {
            get {
                return ResourceManager.GetString("Session_CountdownWithProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reconnecting to {0}.
        /// </summary>
        public static string Session_ReconnectingTitle {
            get {
                return ResourceManager.GetString("Session_ReconnectingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attempt {0} of {1}..
        /// </summary>
        public static string Session_ReconnectingMessage {
            get {
                return ResourceManager.GetString("Session_ReconnectingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' failed — {1}.
        /// </summary>
        public static string Session_FailedTitle {
            get {
                return ResourceManager.GetString("Session_FailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the connection could not be established.
        /// </summary>
        public static string Session_CouldNotConnect {
            get {
                return ResourceManager.GetString("Session_CouldNotConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} — {1}.
        /// </summary>
        public static string Session_DetailSeparator {
            get {
                return ResourceManager.GetString("Session_DetailSeparator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to retry in {0} s.
        /// </summary>
        public static string Session_Countdown {
            get {
                return ResourceManager.GetString("Session_Countdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnected — {0}.
        /// </summary>
        public static string Session_StateDisconnected {
            get {
                return ResourceManager.GetString("Session_StateDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string Session_StateNotConnected {
            get {
                return ResourceManager.GetString("Session_StateNotConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting….
        /// </summary>
        public static string Session_StateConnecting {
            get {
                return ResourceManager.GetString("Session_StateConnecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Session_StateConnected {
            get {
                return ResourceManager.GetString("Session_StateConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Interrupted (attempt {0}).
        /// </summary>
        public static string Session_StateInterrupted {
            get {
                return ResourceManager.GetString("Session_StateInterrupted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Interrupted — {0} (attempt {1}).
        /// </summary>
        public static string Session_StateInterruptedCountdown {
            get {
                return ResourceManager.GetString("Session_StateInterruptedCountdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reconnecting (attempt {0}).
        /// </summary>
        public static string Session_StateReconnecting {
            get {
                return ResourceManager.GetString("Session_StateReconnecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed — {0}.
        /// </summary>
        public static string Session_StateFailedReason {
            get {
                return ResourceManager.GetString("Session_StateFailedReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Session_StateFailed {
            get {
                return ResourceManager.GetString("Session_StateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closing….
        /// </summary>
        public static string Session_StateClosing {
            get {
                return ResourceManager.GetString("Session_StateClosing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Session_StateClosed {
            get {
                return ResourceManager.GetString("Session_StateClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command palette.
        /// </summary>
        public static string Palette_Title {
            get {
                return ResourceManager.GetString("Palette_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search connections and commands.
        /// </summary>
        public static string Palette_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Palette_SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing to run..
        /// </summary>
        public static string Palette_EmptyNothingToRun {
            get {
                return ResourceManager.GetString("Palette_EmptyNothingToRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No connection or command matches “{0}”..
        /// </summary>
        public static string Palette_EmptyNoMatch {
            get {
                return ResourceManager.GetString("Palette_EmptyNoMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch to {0}.
        /// </summary>
        public static string Palette_SwitchToTab {
            get {
                return ResourceManager.GetString("Palette_SwitchToTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} · {1}.
        /// </summary>
        public static string Palette_ConnectionSubtitle {
            get {
                return ResourceManager.GetString("Palette_ConnectionSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New connection.
        /// </summary>
        public static string Palette_NewConnection {
            get {
                return ResourceManager.GetString("Palette_NewConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a machine to the list without connecting to it.
        /// </summary>
        public static string Palette_NewConnectionSubtitle {
            get {
                return ResourceManager.GetString("Palette_NewConnectionSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import connections….
        /// </summary>
        public static string Palette_ImportConnections {
            get {
                return ResourceManager.GetString("Palette_ImportConnections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From .rdp files or the mstsc history.
        /// </summary>
        public static string Palette_ImportSubtitle {
            get {
                return ResourceManager.GetString("Palette_ImportSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage credentials….
        /// </summary>
        public static string Palette_ManageCredentials {
            get {
                return ResourceManager.GetString("Palette_ManageCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Review or delete the user names and passwords already saved.
        /// </summary>
        public static string Palette_ManageCredentialsSubtitle {
            get {
                return ResourceManager.GetString("Palette_ManageCredentialsSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle connection pane.
        /// </summary>
        public static string Palette_TogglePane {
            get {
                return ResourceManager.GetString("Palette_TogglePane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Give the session the whole window, or bring the list back.
        /// </summary>
        public static string Palette_TogglePaneSubtitle {
            get {
                return ResourceManager.GetString("Palette_TogglePaneSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close current session.
        /// </summary>
        public static string Palette_CloseSession {
            get {
                return ResourceManager.GetString("Palette_CloseSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnect it and close its tab.
        /// </summary>
        public static string Palette_CloseSessionSubtitle {
            get {
                return ResourceManager.GetString("Palette_CloseSessionSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reconnect current tab.
        /// </summary>
        public static string Palette_ReconnectTab {
            get {
                return ResourceManager.GetString("Palette_ReconnectTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dial the same machine again after a dropped connection.
        /// </summary>
        public static string Palette_ReconnectTabSubtitle {
            get {
                return ResourceManager.GetString("Palette_ReconnectTabSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detach current session.
        /// </summary>
        public static string Palette_DetachSession {
            get {
                return ResourceManager.GetString("Palette_DetachSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pull {0} out into a window of its own.
        /// </summary>
        public static string Palette_DetachSessionSubtitle {
            get {
                return ResourceManager.GetString("Palette_DetachSessionSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reattach this session to the main window.
        /// </summary>
        public static string Palette_ReattachSession {
            get {
                return ResourceManager.GetString("Palette_ReattachSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bring {0} back as a tab of the main window.
        /// </summary>
        public static string Palette_ReattachSessionSubtitle {
            get {
                return ResourceManager.GetString("Palette_ReattachSessionSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Palette_GroupConnections {
            get {
                return ResourceManager.GetString("Palette_GroupConnections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open sessions.
        /// </summary>
        public static string Palette_GroupSessions {
            get {
                return ResourceManager.GetString("Palette_GroupSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Palette_GroupCommands {
            get {
                return ResourceManager.GetString("Palette_GroupCommands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ↑ ↓ navigate · Enter open · Esc close.
        /// </summary>
        public static string Palette_Footer {
            get {
                return ResourceManager.GetString("Palette_Footer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+N.
        /// </summary>
        public static string Palette_ShortcutNewConnection {
            get {
                return ResourceManager.GetString("Palette_ShortcutNewConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+B.
        /// </summary>
        public static string Palette_ShortcutTogglePane {
            get {
                return ResourceManager.GetString("Palette_ShortcutTogglePane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+W.
        /// </summary>
        public static string Palette_ShortcutCloseSession {
            get {
                return ResourceManager.GetString("Palette_ShortcutCloseSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+D.
        /// </summary>
        public static string Palette_ShortcutDetach {
            get {
                return ResourceManager.GetString("Palette_ShortcutDetach", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Editor_Title {
            get {
                return ResourceManager.GetString("Editor_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Editor_SectionGeneral {
            get {
                return ResourceManager.GetString("Editor_SectionGeneral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        public static string Editor_Name {
            get {
                return ResourceManager.GetString("Editor_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host *.
        /// </summary>
        public static string Editor_Host {
            get {
                return ResourceManager.GetString("Editor_Host", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to server.example.com.
        /// </summary>
        public static string Editor_HostPlaceholder {
            get {
                return ResourceManager.GetString("Editor_HostPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Editor_Port {
            get {
                return ResourceManager.GetString("Editor_Port", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Editor_Group {
            get {
                return ResourceManager.GetString("Editor_Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Editor_Favorite {
            get {
                return ResourceManager.GetString("Editor_Favorite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        public static string Editor_SectionSignIn {
            get {
                return ResourceManager.GetString("Editor_SectionSignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credential.
        /// </summary>
        public static string Editor_Credential {
            get {
                return ResourceManager.GetString("Editor_Credential", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Editor_Authentication {
            get {
                return ResourceManager.GetString("Editor_Authentication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use web account (experimental).
        /// </summary>
        public static string Editor_UseWebAccount {
            get {
                return ResourceManager.GetString("Editor_UseWebAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Editor_SectionDisplay {
            get {
                return ResourceManager.GetString("Editor_SectionDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display mode.
        /// </summary>
        public static string Editor_DisplayMode {
            get {
                return ResourceManager.GetString("Editor_DisplayMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fixed size.
        /// </summary>
        public static string Editor_FixedSize {
            get {
                return ResourceManager.GetString("Editor_FixedSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to width.
        /// </summary>
        public static string Editor_WidthPlaceholder {
            get {
                return ResourceManager.GetString("Editor_WidthPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        public static string Editor_HeightPlaceholder {
            get {
                return ResourceManager.GetString("Editor_HeightPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redirections.
        /// </summary>
        public static string Editor_SectionRedirections {
            get {
                return ResourceManager.GetString("Editor_SectionRedirections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Editor_RedirectClipboard {
            get {
                return ResourceManager.GetString("Editor_RedirectClipboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string Editor_RedirectDrives {
            get {
                return ResourceManager.GetString("Editor_RedirectDrives", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        public static string Editor_RedirectPrinters {
            get {
                return ResourceManager.GetString("Editor_RedirectPrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Editor_RedirectAudio {
            get {
                return ResourceManager.GetString("Editor_RedirectAudio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Editor_SectionAdvanced {
            get {
                return ResourceManager.GetString("Editor_SectionAdvanced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin session (/admin).
        /// </summary>
        public static string Editor_AdminSession {
            get {
                return ResourceManager.GetString("Editor_AdminSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string Editor_NotesPlaceholder {
            get {
                return ResourceManager.GetString("Editor_NotesPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check the form.
        /// </summary>
        public static string Editor_CheckFormTitle {
            get {
                return ResourceManager.GetString("Editor_CheckFormTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not save.
        /// </summary>
        public static string Editor_CouldNotSaveTitle {
            get {
                return ResourceManager.GetString("Editor_CouldNotSaveTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string Editor_CredentialNone {
            get {
                return ResourceManager.GetString("Editor_CredentialNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Editor_AuthDefault {
            get {
                return ResourceManager.GetString("Editor_AuthDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No server auth.
        /// </summary>
        public static string Editor_AuthNoServerAuth {
            get {
                return ResourceManager.GetString("Editor_AuthNoServerAuth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Editor_AuthRequired {
            get {
                return ResourceManager.GetString("Editor_AuthRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prompt if failed.
        /// </summary>
        public static string Editor_AuthPromptIfFailed {
            get {
                return ResourceManager.GetString("Editor_AuthPromptIfFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        public static string Editor_DisplayDynamic {
            get {
                return ResourceManager.GetString("Editor_DisplayDynamic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scaled.
        /// </summary>
        public static string Editor_DisplayScaled {
            get {
                return ResourceManager.GetString("Editor_DisplayScaled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string Editor_DisplayFixed {
            get {
                return ResourceManager.GetString("Editor_DisplayFixed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credential.
        /// </summary>
        public static string CredEditor_Title {
            get {
                return ResourceManager.GetString("CredEditor_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Label *.
        /// </summary>
        public static string CredEditor_Label {
            get {
                return ResourceManager.GetString("CredEditor_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User name *.
        /// </summary>
        public static string CredEditor_UserName {
            get {
                return ResourceManager.GetString("CredEditor_UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        public static string CredEditor_DomainPlaceholder {
            get {
                return ResourceManager.GetString("CredEditor_DomainPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        public static string CredEditor_PasswordRequired {
            get {
                return ResourceManager.GetString("CredEditor_PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string CredEditor_Password {
            get {
                return ResourceManager.GetString("CredEditor_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string CredEditor_PasswordPlaceholderNew {
            get {
                return ResourceManager.GetString("CredEditor_PasswordPlaceholderNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to •••••••• (unchanged — type to replace).
        /// </summary>
        public static string CredEditor_PasswordPlaceholderExisting {
            get {
                return ResourceManager.GetString("CredEditor_PasswordPlaceholderExisting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string CredEditor_PasswordRequiredError {
            get {
                return ResourceManager.GetString("CredEditor_PasswordRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not save: {0}.
        /// </summary>
        public static string CredEditor_CouldNotSave {
            get {
                return ResourceManager.GetString("CredEditor_CouldNotSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Credentials_Title {
            get {
                return ResourceManager.GetString("Credentials_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Credentials_ColumnLabel {
            get {
                return ResourceManager.GetString("Credentials_ColumnLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Credentials_ColumnUser {
            get {
                return ResourceManager.GetString("Credentials_ColumnUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Credentials_Add {
            get {
                return ResourceManager.GetString("Credentials_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Credentials_Edit {
            get {
                return ResourceManager.GetString("Credentials_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Credentials_Delete {
            get {
                return ResourceManager.GetString("Credentials_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        public static string Credentials_ConfirmDelete {
            get {
                return ResourceManager.GetString("Credentials_ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete credential?.
        /// </summary>
        public static string Credentials_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("Credentials_DeleteConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' will be removed; connections using it will need a new credential. Click again to confirm..
        /// </summary>
        public static string Credentials_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("Credentials_DeleteConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import connections.
        /// </summary>
        public static string Import_Title {
            get {
                return ResourceManager.GetString("Import_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From a folder….
        /// </summary>
        public static string Import_FromFolder {
            get {
                return ResourceManager.GetString("Import_FromFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read every .rdp file directly inside a folder.
        /// </summary>
        public static string Import_FromFolderToolTip {
            get {
                return ResourceManager.GetString("Import_FromFolderToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From Remote Desktop Connection.
        /// </summary>
        public static string Import_FromRegistry {
            get {
                return ResourceManager.GetString("Import_FromRegistry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read the servers the Windows Remote Desktop client remembers.
        /// </summary>
        public static string Import_FromRegistryToolTip {
            get {
                return ResourceManager.GetString("Import_FromRegistryToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No password is ever imported and no credential is created. Imported connections start without one — add credentials afterwards from Manage credentials. Ticked rows are imported, including the ones flagged as duplicates..
        /// </summary>
        public static string Import_Promise {
            get {
                return ResourceManager.GetString("Import_Promise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Import_ColumnName {
            get {
                return ResourceManager.GetString("Import_ColumnName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host:port.
        /// </summary>
        public static string Import_ColumnAddress {
            get {
                return ResourceManager.GetString("Import_ColumnAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Import_ColumnSource {
            get {
                return ResourceManager.GetString("Import_ColumnSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Import_ColumnStatus {
            get {
                return ResourceManager.GetString("Import_ColumnStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select all new.
        /// </summary>
        public static string Import_SelectAllNew {
            get {
                return ResourceManager.GetString("Import_SelectAllNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Import_Clear {
            get {
                return ResourceManager.GetString("Import_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Import_Close {
            get {
                return ResourceManager.GetString("Import_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import {0} connection.
        /// </summary>
        public static string Import_ButtonOne {
            get {
                return ResourceManager.GetString("Import_ButtonOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import {0} connections.
        /// </summary>
        public static string Import_ButtonMany {
            get {
                return ResourceManager.GetString("Import_ButtonMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Import_StatusNew {
            get {
                return ResourceManager.GetString("Import_StatusNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already imported.
        /// </summary>
        public static string Import_StatusAlreadyImported {
            get {
                return ResourceManager.GetString("Import_StatusAlreadyImported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate of {0}.
        /// </summary>
        public static string Import_StatusDuplicateOf {
            get {
                return ResourceManager.GetString("Import_StatusDuplicateOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already saved as “{0}”..
        /// </summary>
        public static string Import_DetailAlreadySaved {
            get {
                return ResourceManager.GetString("Import_DetailAlreadySaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Another row above targets the same host and port..
        /// </summary>
        public static string Import_DetailDuplicateInBatch {
            get {
                return ResourceManager.GetString("Import_DetailDuplicateInBatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User name “{0}” is not imported: attach a credential instead..
        /// </summary>
        public static string Import_CredentialWarning {
            get {
                return ResourceManager.GetString("Import_CredentialWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose a source above to see what can be imported..
        /// </summary>
        public static string Import_SummaryInitial {
            get {
                return ResourceManager.GetString("Import_SummaryInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} .rdp file in {1}.
        /// </summary>
        public static string Import_HeadRdpFilesOne {
            get {
                return ResourceManager.GetString("Import_HeadRdpFilesOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} .rdp files in {1}.
        /// </summary>
        public static string Import_HeadRdpFilesMany {
            get {
                return ResourceManager.GetString("Import_HeadRdpFilesMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} could not be read.
        /// </summary>
        public static string Import_HeadUnreadableOne {
            get {
                return ResourceManager.GetString("Import_HeadUnreadableOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} could not be read.
        /// </summary>
        public static string Import_HeadUnreadableMany {
            get {
                return ResourceManager.GetString("Import_HeadUnreadableMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} carried no usable address.
        /// </summary>
        public static string Import_HeadHostlessOne {
            get {
                return ResourceManager.GetString("Import_HeadHostlessOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} carried no usable address.
        /// </summary>
        public static string Import_HeadHostlessMany {
            get {
                return ResourceManager.GetString("Import_HeadHostlessMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop Connection remembers no server..
        /// </summary>
        public static string Import_HeadRegistryEmpty {
            get {
                return ResourceManager.GetString("Import_HeadRegistryEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} server remembered by Remote Desktop Connection..
        /// </summary>
        public static string Import_HeadRegistryServersOne {
            get {
                return ResourceManager.GetString("Import_HeadRegistryServersOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} servers remembered by Remote Desktop Connection..
        /// </summary>
        public static string Import_HeadRegistryServersMany {
            get {
                return ResourceManager.GetString("Import_HeadRegistryServersMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} new.
        /// </summary>
        public static string Import_TallyNewOne {
            get {
                return ResourceManager.GetString("Import_TallyNewOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} new.
        /// </summary>
        public static string Import_TallyNewMany {
            get {
                return ResourceManager.GetString("Import_TallyNewMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} already imported.
        /// </summary>
        public static string Import_TallyAlreadyOne {
            get {
                return ResourceManager.GetString("Import_TallyAlreadyOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} already imported.
        /// </summary>
        public static string Import_TallyAlreadyMany {
            get {
                return ResourceManager.GetString("Import_TallyAlreadyMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} duplicate in this batch.
        /// </summary>
        public static string Import_TallyDuplicateOne {
            get {
                return ResourceManager.GetString("Import_TallyDuplicateOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} duplicates in this batch.
        /// </summary>
        public static string Import_TallyDuplicateMany {
            get {
                return ResourceManager.GetString("Import_TallyDuplicateMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Nothing to import..
        /// </summary>
        public static string Import_SummaryNothing {
            get {
                return ResourceManager.GetString("Import_SummaryNothing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} connection: {2}..
        /// </summary>
        public static string Import_SummaryConnectionsOne {
            get {
                return ResourceManager.GetString("Import_SummaryConnectionsOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} connections: {2}..
        /// </summary>
        public static string Import_SummaryConnectionsMany {
            get {
                return ResourceManager.GetString("Import_SummaryConnectionsMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose the folder holding the .rdp files.
        /// </summary>
        public static string Import_FolderDialogTitle {
            get {
                return ResourceManager.GetString("Import_FolderDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read that folder.
        /// </summary>
        public static string Import_FolderFailedTitle {
            get {
                return ResourceManager.GetString("Import_FolderFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read the Remote Desktop history.
        /// </summary>
        public static string Import_RegistryFailedTitle {
            get {
                return ResourceManager.GetString("Import_RegistryFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        /// </summary>
        public static string Import_FailedTitle {
            get {
                return ResourceManager.GetString("Import_FailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} connection imported.
        /// </summary>
        public static string Import_ImportedOne {
            get {
                return ResourceManager.GetString("Import_ImportedOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} connections imported.
        /// </summary>
        public static string Import_ImportedMany {
            get {
                return ResourceManager.GetString("Import_ImportedMany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to They were saved without a credential; add one from Manage credentials when you need it..
        /// </summary>
        public static string Import_ImportedMessage {
            get {
                return ResourceManager.GetString("Import_ImportedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reattach.
        /// </summary>
        public static string SessionWindow_Reattach {
            get {
                return ResourceManager.GetString("SessionWindow_Reattach", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full screen (F11).
        /// </summary>
        public static string SessionWindow_FullScreen {
            get {
                return ResourceManager.GetString("SessionWindow_FullScreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close session.
        /// </summary>
        public static string SessionWindow_Close {
            get {
                return ResourceManager.GetString("SessionWindow_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Session not detached.
        /// </summary>
        public static string Shell_DetachRefusedTitle {
            get {
                return ResourceManager.GetString("Shell_DetachRefusedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be moved to a window of its own and stayed in the main window.
        /// </summary>
        public static string Shell_DetachRefusedMessage {
            get {
                return ResourceManager.GetString("Shell_DetachRefusedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save layout as….
        /// </summary>
        public static string WorkspaceName_Title {
            get {
                return ResourceManager.GetString("WorkspaceName_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WorkspaceName_NameLabel {
            get {
                return ResourceManager.GetString("WorkspaceName_NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PROD.
        /// </summary>
        public static string WorkspaceName_NamePlaceholder {
            get {
                return ResourceManager.GetString("WorkspaceName_NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect the sessions when the workspace opens.
        /// </summary>
        public static string WorkspaceName_AutoConnect {
            get {
                return ResourceManager.GetString("WorkspaceName_AutoConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WorkspaceName_Save {
            get {
                return ResourceManager.GetString("WorkspaceName_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WorkspaceName_Cancel {
            get {
                return ResourceManager.GetString("WorkspaceName_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A workspace needs a name..
        /// </summary>
        public static string WorkspaceName_NameRequired {
            get {
                return ResourceManager.GetString("WorkspaceName_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace “{0}”?.
        /// </summary>
        public static string WorkspaceName_ReplaceTitle {
            get {
                return ResourceManager.GetString("WorkspaceName_ReplaceTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A workspace called “{0}” already exists. Saving replaces what it holds — there is no undo..
        /// </summary>
        public static string WorkspaceName_ReplaceMessage {
            get {
                return ResourceManager.GetString("WorkspaceName_ReplaceMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string WorkspaceName_Replace {
            get {
                return ResourceManager.GetString("WorkspaceName_Replace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workspaces.
        /// </summary>
        public static string Palette_GroupWorkspaces {
            get {
                return ResourceManager.GetString("Palette_GroupWorkspaces", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save layout as….
        /// </summary>
        public static string Palette_SaveLayout {
            get {
                return ResourceManager.GetString("Palette_SaveLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember the open sessions and where they sit.
        /// </summary>
        public static string Palette_SaveLayoutSubtitle {
            get {
                return ResourceManager.GetString("Palette_SaveLayoutSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open workspace “{0}”.
        /// </summary>
        public static string Palette_OpenWorkspace {
            get {
                return ResourceManager.GetString("Palette_OpenWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} connections.
        /// </summary>
        public static string Palette_OpenWorkspaceSubtitle {
            get {
                return ResourceManager.GetString("Palette_OpenWorkspaceSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete workspace “{0}”.
        /// </summary>
        public static string Palette_DeleteWorkspace {
            get {
                return ResourceManager.GetString("Palette_DeleteWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removes the workspace, never the connections.
        /// </summary>
        public static string Palette_DeleteWorkspaceSubtitle {
            get {
                return ResourceManager.GetString("Palette_DeleteWorkspaceSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reopen last session at startup.
        /// </summary>
        public static string Palette_ToggleRestore {
            get {
                return ResourceManager.GetString("Palette_ToggleRestore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currently: {0}.
        /// </summary>
        public static string Palette_ToggleRestoreSubtitle {
            get {
                return ResourceManager.GetString("Palette_ToggleRestoreSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string Palette_On {
            get {
                return ResourceManager.GetString("Palette_On", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string Palette_Off {
            get {
                return ResourceManager.GetString("Palette_Off", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workspace “{0}” saved.
        /// </summary>
        public static string Shell_WorkspaceSaved {
            get {
                return ResourceManager.GetString("Shell_WorkspaceSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} connections and where each one sits..
        /// </summary>
        public static string Shell_WorkspaceSavedMessage {
            get {
                return ResourceManager.GetString("Shell_WorkspaceSavedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing to open.
        /// </summary>
        public static string Shell_WorkspaceEmptyTitle {
            get {
                return ResourceManager.GetString("Shell_WorkspaceEmptyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to “{0}” no longer references any existing connection..
        /// </summary>
        public static string Shell_WorkspaceEmptyMessage {
            get {
                return ResourceManager.GetString("Shell_WorkspaceEmptyMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete “{0}”?.
        /// </summary>
        public static string Shell_DeleteWorkspaceTitle {
            get {
                return ResourceManager.GetString("Shell_DeleteWorkspaceTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The workspace is removed. The connections it lists are left untouched..
        /// </summary>
        public static string Shell_DeleteWorkspaceMessage {
            get {
                return ResourceManager.GetString("Shell_DeleteWorkspaceMessage", resourceCulture);
            }
        }
    }
}
