using System.Globalization;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace RemoteDeck.Core.Tests.Conventions;

/// <summary>
/// Guards the three files that have to agree for a localized string to exist at runtime:
/// <c>Strings.resx</c>, <c>Strings.fr.resx</c> and <c>Strings.Designer.cs</c>.
///
/// The designer file is <strong>committed to source control in this repository, not regenerated by
/// the build</strong>, so every new string is added to it by hand. A key added to the two resx files
/// and forgotten in the designer does not fail the build: it fails at runtime, silently, as a
/// missing label — and until these tests existed, nothing but a careful reader stood in the way.
/// </summary>
public sealed class LocalizationTests
{
    private static readonly Regex PlaceholderPattern = new(@"\{(\d+)\}", RegexOptions.Compiled);

    /// <summary>Property name → the key its getter passes to <c>GetString</c>.</summary>
    private static readonly Regex DesignerPropertyPattern = new(
        @"public\s+static\s+string\s+(?<property>\w+)\s*\{\s*get\s*\{\s*return\s+ResourceManager\.GetString\(""(?<key>[^""]+)""",
        RegexOptions.Compiled);

    private static IReadOnlyDictionary<string, string> ReadResx(string path) =>
        XDocument.Load(path).Root!
            .Elements("data")
            .Where(d => d.Attribute("name") is not null)
            .ToDictionary(
                d => d.Attribute("name")!.Value,
                d => d.Element("value")?.Value ?? string.Empty,
                StringComparer.Ordinal);

    [Fact]
    public void Every_english_key_has_a_french_translation()
    {
        var english = ReadResx(RepoFiles.EnglishResx);
        var french = ReadResx(RepoFiles.FrenchResx);

        var missing = english.Keys.Except(french.Keys, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();

        Assert.True(missing.Count == 0,
            $"Missing from Strings.fr.resx: {string.Join(", ", missing)}. A French interface would fall "
            + "back to the English text for these.");
    }

    [Fact]
    public void The_french_file_carries_no_key_the_english_one_lost()
    {
        var english = ReadResx(RepoFiles.EnglishResx);
        var french = ReadResx(RepoFiles.FrenchResx);

        var orphans = french.Keys.Except(english.Keys, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();

        Assert.True(orphans.Count == 0,
            $"Only in Strings.fr.resx: {string.Join(", ", orphans)}. Either the English key was renamed "
            + "and the French one was not, or this is a translation nothing reads any more.");
    }

    [Fact]
    public void Every_key_has_a_designer_property_that_matches_it()
    {
        var english = ReadResx(RepoFiles.EnglishResx);
        var designer = File.ReadAllText(RepoFiles.DesignerFile);
        var properties = DesignerPropertyPattern.Matches(designer)
            .ToDictionary(m => m.Groups["property"].Value, m => m.Groups["key"].Value, StringComparer.Ordinal);

        var missing = english.Keys.Where(k => !properties.ContainsKey(k)).Order(StringComparer.Ordinal).ToList();

        Assert.True(missing.Count == 0,
            $"No property in Strings.Designer.cs for: {string.Join(", ", missing)}. That file is versioned, "
            + "not generated — add the property by hand, following the ones already there.");
    }

    [Fact]
    public void Every_designer_property_looks_up_the_key_it_is_named_after()
    {
        // The failure this catches is a copy-paste: a new property block keeping the previous
        // block's GetString argument. It compiles, it is used, and it silently shows another
        // string's text.
        var designer = File.ReadAllText(RepoFiles.DesignerFile);

        var mismatched = DesignerPropertyPattern.Matches(designer)
            .Where(m => m.Groups["property"].Value != m.Groups["key"].Value)
            .Select(m => $"{m.Groups["property"].Value} → GetString(\"{m.Groups["key"].Value}\")")
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(mismatched.Count == 0,
            $"Property name and resource key disagree: {string.Join(", ", mismatched)}.");
    }

    [Fact]
    public void Every_designer_property_points_at_a_key_that_exists()
    {
        var english = ReadResx(RepoFiles.EnglishResx);
        var designer = File.ReadAllText(RepoFiles.DesignerFile);

        var dangling = DesignerPropertyPattern.Matches(designer)
            .Select(m => m.Groups["key"].Value)
            .Where(k => !english.ContainsKey(k))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(dangling.Count == 0,
            $"Strings.Designer.cs exposes properties for keys that no longer exist in Strings.resx: "
            + $"{string.Join(", ", dangling)}. Reading one returns null at runtime.");
    }

    [Fact]
    public void Both_languages_use_the_same_placeholders_for_a_key()
    {
        // A {1} dropped in translation is a FormatException in production, in the language nobody
        // on the team reads the logs in.
        var english = ReadResx(RepoFiles.EnglishResx);
        var french = ReadResx(RepoFiles.FrenchResx);

        var problems = new List<string>();
        foreach (var (key, englishValue) in english)
        {
            if (!french.TryGetValue(key, out var frenchValue)) continue;

            var inEnglish = Tokens(englishValue);
            var inFrench = Tokens(frenchValue);
            if (!inEnglish.SetEquals(inFrench))
            {
                problems.Add($"{key} (en: {Format(inEnglish)}, fr: {Format(inFrench)})");
            }
        }

        Assert.True(problems.Count == 0,
            $"Placeholders differ between the two languages: {string.Join("; ", problems.Order(StringComparer.Ordinal))}.");

        static HashSet<int> Tokens(string value) =>
            [.. PlaceholderPattern.Matches(value).Select(m => int.Parse(m.Groups[1].Value, CultureInfo.InvariantCulture))];

        static string Format(HashSet<int> tokens) =>
            tokens.Count == 0 ? "none" : string.Join(",", tokens.Order().Select(t => $"{{{t}}}"));
    }

    [Fact]
    public void No_key_is_left_without_a_value()
    {
        var problems = new[] { RepoFiles.EnglishResx, RepoFiles.FrenchResx }
            .SelectMany(path => ReadResx(path)
                .Where(kv => string.IsNullOrWhiteSpace(kv.Value))
                .Select(kv => $"{Path.GetFileName(path)}:{kv.Key}"))
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(problems.Count == 0, $"Empty resource values: {string.Join(", ", problems)}.");
    }
}
